typography_spectrum: 0.2476331638172269
color:
  brandStrength: 0.697402051417157
  lightness: 0.9682689856272191
  saturation: 0.9506488593760878
  rhythmicContrast: 0.2662325163837522
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
layout_spectrum: 0.8057627873495221
name: F R E S H
navigation:
  - name: Moda & Belleza
    id: 66571a98-f91c-415f-802b-6ea9ba0512ac
    type: content
  - name: Viajes & Lugares
    id: 2da77a06-5cf4-42f9-8f7d-374efa3d749f
    type: content
  - name: Sobre nosotros
    id: 809c411a-8e05-44e8-a848-bfe8b77c28bd
    type: content
title: F R E S H
content: []
description: 'Buscamos inspirarte, mostrándote lo más Fresh!'
purpose:
  - type: external
    url: 'https://www.facebook.com/revistafreshcolombia/'
    label: 'https://www.facebook.com/revistafreshcolombia/'
